language: go

go:
  - 1.12.x

# Only clone the most recent commit.
git:
  depth: 1

#install:
  #- Install stuff
 
script:
  - echo Building...
  - go build github.com/quaggoth/ciproject

deploy:
  provider: releases
  api_key:
    secure: "XAI/5FlZl3v1gpGLjMHPHuR0eYO53VZQEC517Sxkrv9ueJVyysT98AMPRhVHAy0jgmQpZb61s8nyOxWXWcth/ocYYv0sTvJ/CvK4F+gVozFUTPUWR/A++bd8AUnuCxyKfjO9NA9sNpRn7cveNLOwauQGn8R728F0Z4GbWLlAty+9j+EwG/HStOl6V0vsIE5Mu5+p7WybW01LucKaBmHvcJ+g511Id60Ji92X2iYADM8NowYIwwiKR2p3J5nZOqS2jkkNCeglONaHa7fYU4wsENnpgpe59EAn2pLwJUPSj+xqbkE4PrVD+fGH7UyvbXSbZVnM+kUXy4HYCxSEdaREJghaPdmto7biSJWdNrcJVjWvPFXKX7/9XMmozLBGKJCSkoC7etsqhLXq71+j4S/X31SCl31xbSxRZV0rt/f55H4EZsbZYnjxIkzsV/0oABSknKURhZf78vfkdClG53P3hUbaiOc9vH9Ay3uYOPzIJx3M/SosF3khztIRFHruVtEs31aqi7FXfhKKnvfBZ40gTUpOKpU6MXwNnGwkFfvkEOuaVckNzJ/lv47Qq/1eX9NSqMBp/Ahng8jlpqxta+ElXCtUKs0sXullGVbBVVk+Hd7sKjcQsI3KaUVxtolaapg65xdZrxZ8WmRe30IJgVYPvPH8I6lWlMQDKaKP6DVttrg="
  file: "ciproject"
  skip_cleanup: true
  on:
    tags: true
