language: go

go:
  - 1.12.x

# Only clone the most recent commit.
git:
  depth: 1

#install:
  #- Install stuff
 
script:
  - echo Building...
  - |
    if [ ! -d /home/travis/gopath/src/github.com/quaggoth ]; then
      mv /home/travis/gopath/src/github.com/* /home/travis/gopath/src/github.com/quagoth
    fi
  - go build github.com/quaggoth/ciproject

deploy:
  provider: releases
  api_key:
    secure: XxC2ng4lCThn6WSf8bDMPolPnOAWTXALYDtHazP4DfzGhDtALLhrLsjR0cZuhHWh+wd0E++0D2sK08t7kajDWkGcmWh1vVBz1YBI6XYHyasJl9wgsIzNvDpzNrKB8cnD96tUUXDxQu1iC3WGQlNLOIbDRWM3UGd0lsMpKkSuMLODQN1XJRXeAWXTISaXs83ONy/QRxpqCGQlDAwZ4vNqXGOgRkrqwg1CWu+tFrAY0f0wkGjC+uAl2523hDcjRqVkdOyBLrYnlPmWIwcYsqRCxt3GAI6MGkd24f/7kDZOW+WLIGl8ZjTHDZoflvjE7lrOqrUVIa1MRSVNqXIxT35OCih4uAGx/NKrVZpGnzlpU89co//mpYwhbMX5PUgcZMTEdpc5WL0EM3UyAnVhl2rKsDX927pyvhuXNkoZ9cRGHtyfbPQqYQIfYTYWa9IVGUe16hHoltaQGud44VYHpa/v52HeBrHacP/Qy1kuaZ9eLsT2s4SzQYk6CHM3sxh3Fuph4ObSXGmnwamPPitJRZPQo58s64ks5tw/ltR2T3hmsJFh2nCe6RzboxuhNbVkeezsZpY8XIWDaER5w2LoYK/HOp70p3uN2KMOe8RX49oJFONDs/HTjrXPgy6PpuW6UbMVr6u6aRfjYw459pQTDagjFr4laxDKOpzwEkiT6Jhob94=
  file: "ciproject"
  skip_cleanup: true
  draft: true
  on:
    tags: true
