language: go

go:
  - 1.12.x

# Only clone the most recent commit.
git:
  depth: 1

#install:
  #- Install stuff
 
script:
  - echo Building...
  - go build github.com/quaggoth/ciproject

deploy:
  provider: releases
  api_key:
    secure: XxC2ng4lCThn6WSf8bDMPolPnOAWTXALYDtHazP4DfzGhDtALLhrLsjR0cZuhHWh+wd0E++0D2sK08t7kajDWkGcmWh1vVBz1YBI6XYHyasJl9wgsIzNvDpzNrKB8cnD96tUUXDxQu1iC3WGQlNLOIbDRWM3UGd0lsMpKkSuMLODQN1XJRXeAWXTISaXs83ONy/QRxpqCGQlDAwZ4vNqXGOgRkrqwg1CWu+tFrAY0f0wkGjC+uAl2523hDcjRqVkdOyBLrYnlPmWIwcYsqRCxt3GAI6MGkd24f/7kDZOW+WLIGl8ZjTHDZoflvjE7lrOqrUVIa1MRSVNqXIxT35OCih4uAGx/NKrVZpGnzlpU89co//mpYwhbMX5PUgcZMTEdpc5WL0EM3UyAnVhl2rKsDX927pyvhuXNkoZ9cRGHtyfbPQqYQIfYTYWa9IVGUe16hHoltaQGud44VYHpa/v52HeBrHacP/Qy1kuaZ9eLsT2s4SzQYk6CHM3sxh3Fuph4ObSXGmnwamPPitJRZPQo58s64ks5tw/ltR2T3hmsJFh2nCe6RzboxuhNbVkeezsZpY8XIWDaER5w2LoYK/HOp70p3uN2KMOe8RX49oJFONDs/HTjrXPgy6PpuW6UbMVr6u6aRfjYw459pQTDagjFr4laxDKOpzwEkiT6Jhob94=
    #secure: UgMKtLVSpReY8VwNseEoqg2si9esGfllOlJUjyq+UYwlOvKW777lOWa+tCByGGsUDlDQ1mgnhcqkboI1zdHAplRm8CcP9VNEi9J/4PoRs5nbj1CNLFucxr72cQ7Amsx9FI6tgSgAg5pLMB6Eq+l7i1g4+jB0KmhVVnFLEtMnSK43YREWj2QKhuHxT1prGtzMVpJ2uzRhG7HLj7E2iCd8xTfuIZZPNTIu+TNyF4SnGSo/dXS7yFXBz6lQPOg2ks/fTwW3UKmqd3hQ/N3p2SKPMTvZVcVv22UO4YPpC8YJ1dDLhrRcbsTPeSNB+txv3wZj9+OY/l5LeYLojuh92DFPUlWEZzSOvrsH/35k71Q8zhnb14+erbzu2pwlmbtOHsj+e4gVTSHx2ULJEzikyE5Sq+lJ8arAeXyK7RaVfOSUtoi73bBLQRwNJW86OL8kVwtKJVsSnWu3BAx73hVhS+z8Mld5UuawFrvuoa2c5JczYjlwMunmdNVUdvJvbS1Ib7AneDgrTrIwhYdDZWgArP8iFJUgBOwmyX4GnhcikuTTowUK4sRgTfWYzDzaErB9T9fkqjd30kCg11UJsFGOzj9C8d0jly0P+24Hx0XIeNvW9Sjm3QAXEbBR/JiKkatF4EeKJq0E7nnRNVXIGOCfXz7peebiSN7xGnBsXIYFZM+GQTE=
  file: "ciproject"
  skip_cleanup: true
  draft: true
  on:
    tags: true
