language: go

go:
  - 1.12.x

# Only clone the most recent commit.
git:
  depth: 1

#install:
  #- Install stuff
 
script:
  - echo Building...
  - go build github.com/quaggoth/ciproject

deploy:
  provider: releases
  api_key:
    secure: "HEZOhaaBI2uJ88zVAYJN+oMqUYqPVWo314nVdtEFbNNYc4oIFIKyRegyD3Td0o9BO+E/9Y7FGw8kHSRFFvIERHSDPA6BnW3xRT5CBeBwv4MOwzP7c4edUhDOkLg9qZh7PH2U3rH4xTY5oMYkruLC58kMNS0Xm/R8eFM4QkLaFrkIKCYvxBcIdODms3+afb9WaRturioKEn7QSr8KegG6DfU0vuVi0Q9jFEtL0vW/zpDWEnq3asNKwcFLYoQ4fVpXysFVdwt75THmaLQ1Ag4wltqarOx/QjR9+XBwMuYHCsSu/40XCKQ+Zz6pxKhjZMix4erAwPnDNKGyf+Ad8EwfPMTpJNJjQHxRKEZwv3Q09dxeMef7gQ1GBZt9VQLeCglWOjaqbmUADlmzhmGLuc0CivlaUZwSY/qfyYUiFPwKG21gmSPDfZSVFy3DGH3a1yQYApCTVwtnH1D/Rv3e0f/GSEt0QJW2rGlblb0nNlmhviXKYs++o6bViInfDu01tXsrp7+WFM7qHrwNEDHgvWCB/UMKS8JwnfpehUAqP8rI2lGjJByrMhJxr4K4HHGy66Jr1HubCLrM+gHS6ADWvsppNRlTJtFl/Huv3OKTfZeA5+z9y0Whconr/xdBs9yFUjYbGpYLv8VQ++fbu3ULlZ1ZjPx3YL8b/Sm6uEwnobCuoRo="
  file: "ciproject"
  skip_cleanup: true
  on:
    tags: true
